export const SampleData = {
    "arxiv": {
        "abstract": "Shape priors have been widely utilized in medical image segmentation to improve segmentation accuracy and robustness. A major way to encode such a prior shape model is to use a mesh representation, which is prone to causing self-intersection or mesh folding. Those problems require complex and expensive algorithms to mitigate. In this paper, we propose a novel shape prior directly embedded in the voxel grid space, based on gradient vector flows of a pre-segmentation. The flexible and powerful prior shape representation is ready to be extended to simultaneously segmenting multiple interacting objects with minimum separation distance constraint. The segmentation problem of multiple interacting objects with shape priors is formulated as a Markov Random Field problem, which seeks to optimize the label assignment (objects or background) for each voxel while keeping the label consistency between the neighboring voxels. The optimization problem can be efficiently solved with a single minimum s-t cut in an appropriately constructed graph. The proposed algorithm has been validated on two multi-object segmentation applications: the brain tissue segmentation in MRI images and the bladder/prostate segmentation in CT images. Both sets of experiments showed superior or competitive performance of the proposed method to the compared state-of-the-art methods."
    },
    "doi": {
        "abstract": "Correspondence Braulio Morales-Martínez, Departamento de Física, Facultad de Ciencias, Universidad Nacional Autónoma de México, A.P. 50-542, Ciudad de México 04510, México Email: jorgebraulio@ciencias.unam.mx We outline the modifications in the numerical Boltzmann code Cosmic Linear Anisotropy Solving System (CLASS) in order to include extra inflationary fields. The functioning of the code is first described, how and where modifications are meant to be done are later explained. In the present study, we focus on the modifications needed for the implementation of a two-field inflationary model, with canonical kinetic terms and a polynomial potential with no cross terms, presenting preliminary results for the effect of the second field on the spectra. The adaptability of the code is exploited, making use of the classes and structures of C and the generic Runge-Kutta integration tool provided by the program.",
    },
    "SemanticScholar": {
        "abstract": "Open Information Extraction (IE) is the task of extracting assertions from massive corpora without requiring a pre-specified vocabulary. This paper shows that the output of state-of-the-art Open IE systems is rife with uninformative and incoherent extractions. To overcome these problems, we introduce two simple syntactic and lexical constraints on binary relations expressed by verbs. We implemented the constraints in the ReVerb Open IE system, which more than doubles the area under the precision-recall curve relative to previous extractors such as TextRunner and woepos. More than 30% of ReVerb's extractions are at precision 0.8 or higher---compared to virtually none for earlier systems. The paper concludes with a detailed analysis of ReVerb's errors, suggesting directions for future work."
    }
}

it('should',() => {
    // Dummy 
})