export const SampleData = {
    "arxiv": {
        "abstract": "Shape priors have been widely utilized in medical image segmentation to improve segmentation accuracy and robustness. A major way to encode such a prior shape model is to use a mesh representation, which is prone to causing self-intersection or mesh folding. Those problems require complex and expensive algorithms to mitigate. In this paper, we propose a novel shape prior directly embedded in the voxel grid space, based on gradient vector flows of a pre-segmentation. The flexible and powerful prior shape representation is ready to be extended to simultaneously segmenting multiple interacting objects with minimum separation distance constraint. The segmentation problem of multiple interacting objects with shape priors is formulated as a Markov Random Field problem, which seeks to optimize the label assignment (objects or background) for each voxel while keeping the label consistency between the neighboring voxels. The optimization problem can be efficiently solved with a single minimum s-t cut in an appropriately constructed graph. The proposed algorithm has been validated on two multi-object segmentation applications: the brain tissue segmentation in MRI images and the bladder/prostate segmentation in CT images. Both sets of experiments showed superior or competitive performance of the proposed method to the compared state-of-the-art methods.",
        "arxivId": "1705.10311"
    },
    "doi": {
        "abstract": "Correspondence Braulio Morales-Martínez, Departamento de Física, Facultad de Ciencias, Universidad Nacional Autónoma de México, A.P. 50-542, Ciudad de México 04510, México Email: jorgebraulio@ciencias.unam.mx We outline the modifications in the numerical Boltzmann code Cosmic Linear Anisotropy Solving System (CLASS) in order to include extra inflationary fields. The functioning of the code is first described, how and where modifications are meant to be done are later explained. In the present study, we focus on the modifications needed for the implementation of a two-field inflationary model, with canonical kinetic terms and a polynomial potential with no cross terms, presenting preliminary results for the effect of the second field on the spectra. The adaptability of the code is exploited, making use of the classes and structures of C and the generic Runge-Kutta integration tool provided by the program.",
        "id": "10.1002/asna.202113881"
    },
    "SemanticScholar": {
        "abstract": "Creating a knowledge graph automatically from raw unstructured text has always been a job of domain expert which takes months to curate and refine. In this paper, we propose a domain-independent semi-automatic knowledge graph learning system that can be trained with less amount of data, to identify entities and relations from a large text corpus. The system performs the following tasks to extract knowledge graph from the text: (i) Named Entity Recognition (NER), and (ii) Relation Identification (Open Relation Extraction (OpenRE) and Classification). The system uses deep active learning to calculate confidence scores using maximum normalized log-probability on each prediction for both NER, and relation identification. We experimented with both LSTM and transformer based models for NER and relation identification tasks.We achieved around 88% F1 score for the NER task on OntoNotes-5.0 English data set with 40% training data set and above 83% F1 score for relation identification on TACRED dataset. The OpenRE and relation classification systems were trained on domain-specific datasets. To the best of our knowledge, we are the first to introduce a knowledge graph generation learning system with deep active learning.",
        "id": "ef6d82d7ae204a4784084c6d7798c4c0dd94c1ce"
    }
}

it('should', () => {
    // Dummy 
})